### ISSUE TITLE
Default to page title if no page is selected

### ISSUE THREAD

**Issue by waldyrious** [shimo164/rich-text-copy#12]
I often want to copy a link to a specific page using the page's title (`<title>` in the HTML) rather than any selected text.

It would be nice if, when no text is selected, this extension defaulted to copying the link to the current page using the title as the link label, rather than doing nothing when the button is clicked as is the current behavior.

**Comment by shimo164** [comment]
@waldyrious Thank you for your comment! That feature was on the list when I developed, but didn't add as the low priority. It's nice to hear that. I will add the feature in the next update.

**Comment by shimo164** [comment]
TODO
- Add the "title mode" checkbox in the Options page.
- When the "title mode" is checked,  
  - the context menu appears with a right click (without any text selection) 
  - we can copy the title and the url of the page

**Comment by waldyrious** [comment]
Nice to see this implemented! However, it doesn't seem to be working for me. I'm already in v1.2, but Clicking the icon without any text selected doesn't copy anything to the clipboard, and right-clicking without selecting some text before also does not show any entry in the context menu. Any hints as to how to troubleshoot this?

**Comment by shimo164** [comment]
@waldyrious Sorry, I didn't add the icon click action for title-url copy this time. I'll take care of it in the feature update.
