### ISSUE TITLE
Add right-click entry

### ISSUE THREAD

**Issue by waldyrious** [shimo164/rich-text-copy#13]
It can be more convenient (especially for people with disabilities) to right-click the mouse and reach for an entry in the context menu, than moving the cursor all the way to the top right of the browser window to copy the link to the current page.

It would be nice to have the option (even if it is disabled by default in the extension preferences) to show an entry in the right click menu that would do the same thing as the extension button in the browser's toolbar.

**Comment by shimo164** [comment]
@waldyrious 

In my current environment, I can select texts and open the context menu with a right click.

![image](https://github.com/shimo164/rich-text-copy/assets/24565156/71470455-58af-49a9-9105-40ab61b18be7)

Isn't this what your mentioned?

**Comment by waldyrious** [comment]
Oh, right! Sorry for the ambiguity. I meant to have that entry show up in the right-click menu even when no selection is made (although that would make sense once #12 is implemented :smile:). Does that make sense?

**Comment by shimo164** [comment]
OK, I see. So this (#13) can be merged to #12. Thanks!

**Comment by waldyrious** [comment]
Sounds good! I see you've added a comment to #12 specifying this behavior, so I'll close this issue. Thanks!
